### ISSUE TITLE
Dev env basically doesn't work on windows

### ISSUE THREAD

**Issue by cyrilchapon** [arryon/sails-hook-fixtures#13]
Trying to contribute, I noticed the following :

- symlinking raises EPERM on windows when not in elevated environment. Which makes symlink node_modules non viable strategy on windows
- after managing to allow symlinking, I'm gettings this :
```

  2 passing (15s)
  5 failing

  1) Test with weird fixtures :: Should handle a missing "order" attribute:
     Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
    at Timeout.<anonymous> (C:\Users\Cyril\Code\sails-hook-fixtures\node_modules\mocha\lib\runnable.js:226:19)


  2) Test overwriting :: "before all" hook:
     AdapterError: Connection is already registered
    at Object.registerConnection (C:\Users\Cyril\Code\sails-hook-fixtures\node_modules\sails-mysql\lib\connections\register.js:29:58)
    at C:\Users\Cyril\Code\sails-hook-fixtures\node_modules\waterline\lib\waterline.js:198:29
    at C:\Users\Cyril\Code\sails-hook-fixtures\node_modules\async\lib\async.js:181:20
    at Object.async.forEachOf.async.eachOf (C:\Users\Cyril\Code\sails-hook-fixtures\node_modules\async\lib\async.js:233:13)
    at Object.async.forEach.async.each (C:\Users\Cyril\Code\sails-hook-fixtures\node_modules\async\lib\async.js:209:22)
    at Array.async.auto.registerConnections (C:\Users\Cyril\Code\sails-hook-fixtures\node_modules\waterline\lib\waterline.js:171:13)
    at C:\Users\Cyril\Code\sails-hook-fixtures\node_modules\async\lib\async.js:596:38
    at _arrayEach (C:\Users\Cyril\Code\sails-hook-fixtures\node_modules\async\lib\async.js:85:13)
    at Object.async.auto (C:\Users\Cyril\Code\sails-hook-fixtures\node_modules\async\lib\async.js:554:9)
    at Waterline.initialize (C:\Users\Cyril\Code\sails-hook-fixtures\node_modules\waterline\lib\waterline.js:118:9)
    at buildWaterlineOntology (C:\Users\Cyril\Code\sails-hook-fixtures\node_modules\sails-hook-orm\lib\build-waterline-ontology.js:45:19)
    at Array.async.auto._buildOntology (C:\Users\Cyril\Code\sails-hook-fixtures\node_modules\sails-hook-orm\lib\initialize.js:388:7)
    at listener (C:\Users\Cyril\Code\sails-hook-fixtures\node_modules\async\lib\async.js:605:42)
    at C:\Users\Cyril\Code\sails-hook-fixtures\node_modules\async\lib\async.js:544:17
    at _arrayEach (C:\Users\Cyril\Code\sails-hook-fixtures\node_modules\async\lib\async.js:85:13)
    at Immediate.taskComplete (C:\Users\Cyril\Code\sails-hook-fixtures\node_modules\async\lib\async.js:543:13)


  3) Test overwriting :: "before all" hook:
     AdapterError: Connection is already registered
    at Object.registerConnection (C:\Users\Cyril\Code\sails-hook-fixtures\node_modules\sails-mysql\lib\connections\register.js:29:58)
    at C:\Users\Cyril\Code\sails-hook-fixtures\node_modules\waterline\lib\waterline.js:198:29
    at C:\Users\Cyril\Code\sails-hook-fixtures\node_modules\async\lib\async.js:181:20
    at Object.async.forEachOf.async.eachOf (C:\Users\Cyril\Code\sails-hook-fixtures\node_modules\async\lib\async.js:233:13)
    at Object.async.forEach.async.each (C:\Users\Cyril\Code\sails-hook-fixtures\node_modules\async\lib\async.js:209:22)
    at Array.async.auto.registerConnections (C:\Users\Cyril\Code\sails-hook-fixtures\node_modules\waterline\lib\waterline.js:171:13)
    at C:\Users\Cyril\Code\sails-hook-fixtures\node_modules\async\lib\async.js:596:38
    at _arrayEach (C:\Users\Cyril\Code\sails-hook-fixtures\node_modules\async\lib\async.js:85:13)
    at Object.async.auto (C:\Users\Cyril\Code\sails-hook-fixtures\node_modules\async\lib\async.js:554:9)
    at Waterline.initialize (C:\Users\Cyril\Code\sails-hook-fixtures\node_modules\waterline\lib\waterline.js:118:9)
    at buildWaterlineOntology (C:\Users\Cyril\Code\sails-hook-fixtures\node_modules\sails-hook-orm\lib\build-waterline-ontology.js:45:19)
    at Array.async.auto._buildOntology (C:\Users\Cyril\Code\sails-hook-fixtures\node_modules\sails-hook-orm\lib\initialize.js:388:7)
    at listener (C:\Users\Cyril\Code\sails-hook-fixtures\node_modules\async\lib\async.js:605:42)
    at C:\Users\Cyril\Code\sails-hook-fixtures\node_modules\async\lib\async.js:544:17
    at _arrayEach (C:\Users\Cyril\Code\sails-hook-fixtures\node_modules\async\lib\async.js:85:13)
    at Immediate.taskComplete (C:\Users\Cyril\Code\sails-hook-fixtures\node_modules\async\lib\async.js:543:13)

[...] etc etc "AdapterError: Connection is already registered"

```

**Comment by arryon** [comment]
Hi @cyrilchapon, I'm not familiar with this sort of error. Then again, I don't dev on Windows. Does the library itself work? I found this issue in the sails-mysql adapter: https://github.com/balderdashy/sails-mysql/issues/252.

Could you try to apply the suggested fix (https://github.com/balderdashy/sails-mysql/issues/252#issuecomment-142329607) and see if the problem is resolved? If so, this might be sails-mysql related. Thanks!

**Comment by cyrilchapon** [comment]
Hey @arryon. Thanks for your help.

Yes library itself works.

I might not have time to try and fix this, so I'm developping with *sails-disk* which works fine.

**Comment by arryon** [comment]
Alright @cyrilchapon. You can also use the MongoDB or PostgreSQL adaptors, since I believe they will also work. 

The issue will remain open as long as this is not resolved. I will try and make time to test this with the mysql adaptor under linux soon, to rule out the mysql library. If someone else wants to check this, they are welcome too.
