### ISSUE TITLE
error: TypeError: cb is not a function

### ISSUE THREAD

**Issue by joao2507** [arryon/sails-hook-fixtures#9]
when trying to run my project with the following fixtures:
```javascript
// sails/config/local.js
module.exports = {
    fixtures: {
        empty: ['Estado','Pais'],
        order: ['Pais','Estado'],
        Pais: [
            {
                nome: 'Brasil',
                sigla: 'BR'
            }
        ],
        Estado: [
            {
                nome: 'Acre',
                sigla: 'AC',
            }
        ]
    }
};
```
the sails returns the following error:
```
info: Removing existing documents from Estado
info: Removing existing documents from Pais
error: TypeError: cb is not a function
    at bound.module.exports [as destroy] (C:\Users\JoãoGabriel\AppData\Roaming\npm\node_modules\sails\node_modules\waterline\lib\waterline\query\dql\destroy.js:42:14)
    at bound [as destroy] (C:\Users\JoãoGabriel\AppData\Roaming\npm\node_modules\sails\node_modules\lodash\dist\lodash.js:729:21)
    at D:\workspace\showint-server\node_modules\sails-hook-fixtures\lib\util.js:144:20
From previous event:
    at emptyExistingCollections (D:\workspace\showint-server\node_modules\sails-hook-fixtures\lib\index.js:35:20)
    at installFixtures (D:\workspace\showint-server\node_modules\sails-hook-fixtures\lib\index.js:77:5)
    at D:\workspace\showint-server\node_modules\sails-hook-fixtures\lib\index.js:132:21
    at C:\Users\JoãoGabriel\AppData\Roaming\npm\node_modules\sails\lib\app\private\after.js:91:14
    at C:\Users\JoãoGabriel\AppData\Roaming\npm\node_modules\sails\node_modules\async\lib\async.js:251:17
    at done (C:\Users\JoãoGabriel\AppData\Roaming\npm\node_modules\sails\node_modules\async\lib\async.js:132:19)
    at C:\Users\JoãoGabriel\AppData\Roaming\npm\node_modules\sails\node_modules\async\lib\async.js:32:16
    at C:\Users\JoãoGabriel\AppData\Roaming\npm\node_modules\sails\node_modules\async\lib\async.js:248:21
    at Sails.<anonymous> (C:\Users\JoãoGabriel\AppData\Roaming\npm\node_modules\sails\node_modules\async\lib\async.js:572:34)
    at Sails.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at Sails.emit (events.js:166:7)
    at Sails.emitter.emit (C:\Users\JoãoGabriel\AppData\Roaming\npm\node_modules\sails\lib\app\private\after.js:50:11)
    at C:\Users\JoãoGabriel\AppData\Roaming\npm\node_modules\sails\lib\app\private\loadHooks.js:110:15
    at C:\Users\JoãoGabriel\AppData\Roaming\npm\node_modules\sails\node_modules\async\lib\async.js:451:17
    at C:\Users\JoãoGabriel\AppData\Roaming\npm\node_modules\sails\node_modules\async\lib\async.js:441:17
    at _each (C:\Users\JoãoGabriel\AppData\Roaming\npm\node_modules\sails\node_modules\async\lib\async.js:46:13)
    at Immediate.taskComplete (C:\Users\JoãoGabriel\AppData\Roaming\npm\node_modules\sails\node_modules\async\lib\async.js:440:13)
    at processImmediate [as _immediateCallback] (timers.js:383:17) [TypeError: cb is not a function]
```

any idea what is?

**Comment by arryon** [comment]
Looks like something is passed to the destroy function that waterline doesn't like:

https://github.com/balderdashy/waterline/blob/master/lib/waterline/query/dql/destroy.js#L41
```
// If there was something defined in the criteria that would return no results, don't even
  // run the query and just return an empty result set.
  if (criteria === false) {
    return cb(null, []);
  }
```

You could edit the lib and log what the id's of the results are before they are emptied. Is your project hosted somewhere I can check it?

**Comment by joao2507** [comment]
For now my project is running locally, so get to the fixtures work, ascend him to the remote server.

My models:

```
/**
 * Pais.js
 *
 * @description :: TODO: You might write a short summary of how this model works and what it represents here.
 * @docs        :: http://sailsjs.org/#!documentation/models
 */

module.exports = {
    attributes: {
        nome: {
            type: 'string',
            required: true
        },
        sigla: {
            type: 'string',
            required: true,
            unique: true
        },
        estados: {
            collection: 'estado',
            via: 'pais'
        }
    }
};
```

```
/**
 * Estado.js
 *
 * @description :: TODO: You might write a short summary of how this model works and what it represents here.
 * @docs        :: http://sailsjs.org/#!documentation/models
 */

module.exports = {
    attributes: {
        nome: {
            type: 'string',
            required: true
        },
        sigla: {
            type: 'string',
            required: true,
            unique: true
        },
        cidades: {
            collection: 'cidade',
            via: 'uf'
        },
        pais: {
            model: 'pais'
        }
    }
};
```

output on execute sails console:
```
sails> Pais.find().exec(console.log)
undefined
sails> null []
sails> Estado.find().exec(console.log)
undefined
sails> null []
```

**Comment by arryon** [comment]
Interesting, I'm getting 'undefined is not a function'. Looking into it a bit.

**Comment by arryon** [comment]
@joao2507 Turns out Waterline didn't like it whenever I passed an empty result to destroy. I updated the lib, can you retry?

**Comment by joao2507** [comment]
try updating lib:
```
D:\workspace\showint-server>npm install sails-hook-fixtures@0.11.7
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "D:\\Arquivos de Programas\\nodejs\\node.exe" "D:\\Arquivos de Programas\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "sails-hook-fixtures@0.11.7"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12

npm ERR! No compatible version found: sails-hook-fixtures@0.11.7
npm ERR! Valid install targets:
npm ERR! 0.11.6, 0.11.5, 0.11.4, 0.11.3, 0.11.2, 0.11.1, 0.11.0, 0.1.0
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\workspace\showint-server\npm-debug.log
```

**Comment by arryon** [comment]
Ah yes, you're right, I forgot publishing to NPM. It should be installable now

**Comment by joao2507** [comment]
@arryon thanks! now worked here.

**Comment by arryon** [comment]
Alright, I'm closing the issue. Thanks for reporting!
